version: "3.9"
services:

  users-service:
    build:
      dockerfile: build/users.Dockerfile
    restart: unless-stopped
    platform: linux/amd64
    command: [ "./main" ]
    ports:
      - "7001:7001"
    environment:
      DB_NAME: otterside
      DB_SERVICE_HOST: postgres
      DB_SERVICE_USER: postgres
      DB_SERVICE_PASS: password
    depends_on:
      - postgres

  products-service:
    build:
      dockerfile: build/products.Dockerfile
    restart: unless-stopped
    platform: linux/amd64
    command: [ "./main" ]
    ports:
      - "7002:7002"
    environment:
      STORAGE_ENABLED: false
      STORAGE_BUCKET_NAME: bucket-name
      STORAGE_OBJECT_KEY: products.json

  newsletter-service:
    build:
      dockerfile: build/newsletter.Dockerfile
    restart: unless-stopped
    platform: linux/amd64
    command: ["node", "index.js"]
    ports:
      - "7003:7003"
    environment:
      DB_NAME: otterside
      DB_SERVICE_HOST: postgres
      DB_SERVICE_USER: postgres
      DB_SERVICE_PASS: password
    depends_on:
      - postgres

  cart-service:
    build:
      dockerfile: build/cart.Dockerfile
    restart: unless-stopped
    platform: linux/amd64
    ports:
      - "7004:7004"
    environment:
      REDIS_HOST: redis
      PRODUCTS_SERVICE_API: https://products-service:7002
    depends_on:
      - products-service
      - redis

  checkout-service:
    build:
      dockerfile: build/checkout.Dockerfile
    restart: unless-stopped
    platform: linux/amd64
    command: ["node", "index.js"]
    ports:
      - "7005:7005"
    environment:
      CART_SERVICE_API: https://cart-service:7004
    depends_on:
      - cart-service

  frontend-service:
    build:
      dockerfile: build/frontend.Dockerfile
    restart: unless-stopped
    platform: linux/amd64
    ports:
      - "7000:7000"
    environment:
      CART_SERVICE_API: https://cart-service:7004
      USERS_SERVICE_API: https://users-service:7001
      PRODUCTS_SERVICE_API: https://products-service:7002
      CHECKOUT_SERVICE_API: https://checkout-service:7005
      NEWSLETTER_SERVICE_API: https://newsletter-service:7003
    depends_on:
      - cart-service
      - users-service
      - products-service
      - checkout-service
      - newsletter-service

  postgres:
    image: postgres:14
    restart: unless-stopped
    ports:
      - "5432:5432"
    shm_size: 4gb
    environment:
      POSTGRES_DB: otterside
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  postgres:
