version: "3.9"
services:
  users-service:
    build:
      dockerfile: build/users.Dockerfile
    restart: unless-stopped
    platform: linux/amd64
    command: [ "./main" ]
    ports:
      - "7001:7001"
    environment:
      DB_NAME: otterside
      DB_SERVICE_HOST: postgres
      DB_SERVICE_USER: postgres
      DB_SERVICE_PASS: password
    depends_on:
      - postgres

  products-service:
    build:
      dockerfile: build/products.Dockerfile
    restart: unless-stopped
    platform: linux/amd64
    command: [ "./main" ]
    ports:
      - "7002:7002"
    environment:
      STORAGE_ENABLED: false
      STORAGE_BUCKET_NAME: bucket-name
      STORAGE_OBJECT_KEY: products.json

  newsletter-service:
    build:
      dockerfile: build/newsletter.Dockerfile
    restart: unless-stopped
    platform: linux/amd64
    command: ["node", "index.js"]
    ports:
      - "7003:7003"
    environment:
      DB_NAME: otterside
      DB_SERVICE_HOST: postgres
      DB_SERVICE_USER: postgres
      DB_SERVICE_PASS: password
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    restart: unless-stopped
    ports:
      - "5432:5432"
    shm_size: 4gb
    environment:
      POSTGRES_DB: otterside
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  postgres:
