apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: otterside-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: otterside.otterize.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 7000
